import { Inter } from 'next/font/google'
import './globals.css'
import {Providers} from "@/app/providers";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Isaacdle',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
    <head>
      <meta name="google-site-verification" content="mqZ8snknrWo8M6eqI6K-EgoJl-YwUefTCShIIRO6nSc"/>
      <title>Isaacdle - TBOI Wordle</title>
    </head>
    <body>
      <Providers>
        {children}
      </Providers>
    </body>
    </html>
  )
}
