import { Inter } from 'next/font/google'
import './globals.css'
import {Providers} from "@/app/providers";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Isaacdle',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
